package loginn;


import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;


public class Signup extends javax.swing.JFrame {

   
    public Signup() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmailId = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Singup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email ID");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        Singup.setText("Signup");
        Singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingupActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Signup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(Username)
                    .addComponent(Password))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Singup))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Singup)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void SingupActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         if(Username.getText().trim().isEmpty() && Password.getText().trim().isEmpty() && EmailId.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "All fields are empty, please try again");
        }
         else if(Username.getText().trim().isEmpty() && Password.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username and Password cannot be empty");
        }
        else if(Username.getText().trim().isEmpty() && EmailId.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username and Email ID cannot be empty");
        }
        else if(Password.getText().trim().isEmpty() && EmailId.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password and Email ID cannot be empty");
        }
         else if(EmailId.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Email ID cannot be empty");
        }
         else if(Username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username cannot be empty");
        }
        else if(Password.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password cannot be empty");
        }
        
        
        if(true){
        
     
            boolean result = true;
            try {
               InternetAddress emailAddr = new InternetAddress(EmailId.getText());
              emailAddr.validate();
              } catch (AddressException ex) {
             result = false;
             }
             //return result;
             if(result==false){
             
              JOptionPane.showMessageDialog(null, "Enter Valid email Id");
             
             }
 
        
        
        
        
        
        else{
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            String sql= "INSERT INTO login (Email, Username, Password) values (?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,EmailId.getText());
            pst.setString(2,Username.getText());
            pst.setString(3,Password.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Signed Up successfully");
            new LoginFrame().setVisible(true);
            this.setVisible(false);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    
 public static void main(String arg[]) {
    new Signup();
    }


    // Variables declaration - do not modify                     
    private javax.swing.JTextField EmailId;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Singup;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   
}

